// Exact Sentinel VM semantics extracted from the installed Codex Desktop bundle.
let Er,Dr,Or,kr,Ar,jr,Mr,Nr,Pr,F,Fr,Ir,Lr,Rr,zr,Br,Vr,Hr,Ur,Wr,Gr,Kr,qr,Jr,Yr,Xr,Zr,Qr,$r,ei,ti,ni,ri,ii,I,ai,oi;
function xr(e){let t=oi.then(e,e);return oi=t.then(()=>void 0,()=>void 0),t}
async function Sr(){for(;I.get(F).length>0;){let[e,...t]=I.get(F).shift()??[],n=I.get(e)?.(...t);n&&typeof n.then==`function`&&await Promise.resolve(n),ai++}}
function Cr(e,t){return xr(()=>new Promise((n,r)=>{Tr(),ai=0,I.set(Vr,t);let i=!1;setTimeout(()=>{i=!0,n(String(ai))},500),I.set(kr,e=>{i||(i=!0,n(btoa(String(e))))}),I.set(Ar,e=>{i||(i=!0,r(btoa(String(e))))}),I.set(ti,(e,t,n,r)=>{let a=Array.isArray(r),o=a?n:[],s=(a?r:n)??[];I.set(e,(...e)=>{if(i)return;let n=[...I.get(F)];if(a)for(let t=0;t<o.length;t++)I.set(o[t],e[t]);return I.set(F,[...s]),Sr().then(()=>I.get(t)).catch(e=>String(e)).finally(()=>{I.set(F,n)})})});try{I.set(F,JSON.parse(wr(atob(e),String(I.get(Vr))))),Sr().catch(e=>{n(btoa(`${ai}: ${String(e)}`))})}catch(e){n(btoa(`${ai}: ${String(e)}`))}}))}
function wr(e,t){let n=``;for(let r=0;r<e.length;r++)n+=String.fromCharCode(e.charCodeAt(r)^t.charCodeAt(r%t.length));return n}
function Tr(){I.clear(),I.set(Er,e=>Cr(e,String(I.get(Vr)))),I.set(Dr,(e,t)=>I.set(e,wr(String(I.get(e)),String(I.get(t))))),I.set(Or,(e,t)=>I.set(e,t)),I.set(jr,(e,t)=>{let n=I.get(e);if(Array.isArray(n)){n.push(I.get(t));return}I.set(e,n+I.get(t))}),I.set(Qr,(e,t)=>{let n=I.get(e);if(Array.isArray(n)){n.splice(n.indexOf(I.get(t)),1);return}I.set(e,n-I.get(t))}),I.set(ei,(e,t,n)=>I.set(e,Number(I.get(t))<Number(I.get(n)))),I.set(ni,(e,t,n)=>I.set(e,Number(I.get(t))*Number(I.get(n)))),I.set(ii,(e,t,n)=>{let r=Number(I.get(n));I.set(e,r===0?0:Number(I.get(t))/r)}),I.set(Mr,(e,t,n)=>{let r=I.get(t);I.set(e,r[String(I.get(n))])}),I.set(Nr,(e,...t)=>I.get(e)(...t.map(e=>I.get(e)))),I.set(Hr,(e,t,...n)=>{try{let r=I.get(t)(...n.map(e=>I.get(e)));if(r&&typeof r.then==`function`)return r.then(t=>{I.set(e,t)}).catch(t=>{I.set(e,String(t))});I.set(e,r)}catch(t){I.set(e,String(t))}}),I.set(Rr,(e,t,...n)=>{try{I.get(t)(...n)}catch(t){I.set(e,String(t))}}),I.set(Pr,(e,t)=>I.set(e,I.get(t))),I.set(Fr,window),I.set(Ir,(e,t)=>I.set(e,(Array.from(document.scripts||[]).map(e=>e?.src?.match(String(I.get(t)))).filter(e=>e?.length)[0]??[])[0]??null)),I.set(Lr,e=>I.set(e,I)),I.set(zr,(e,t)=>I.set(e,JSON.parse(String(I.get(t))))),I.set(Br,(e,t)=>I.set(e,JSON.stringify(I.get(t)))),I.set(Ur,e=>I.set(e,atob(String(I.get(e))))),I.set(Wr,e=>I.set(e,btoa(String(I.get(e))))),I.set(Gr,(e,t,n,...r)=>I.get(e)===I.get(t)?I.get(n)(...r):null),I.set(Kr,(e,t,n,r,...i)=>Math.abs(Number(I.get(e))-Number(I.get(t)))>Number(I.get(n))?I.get(r)(...i):null),I.set(Jr,(e,t,...n)=>I.get(e)===void 0?null:I.get(t)(...n)),I.set(Yr,(e,t,n)=>{let r=I.get(t),i=r[String(I.get(n))];I.set(e,i.bind(r))}),I.set(ri,(e,t)=>{let n=I.get(t);return Promise.resolve(n).then(t=>{I.set(e,t)})}),I.set(qr,(e,t)=>{let n=[...I.get(F)];return I.set(F,[...t]),Sr().catch(t=>{I.set(e,String(t))}).finally(()=>{I.set(F,n)})}),I.set($r,()=>void 0),I.set(Zr,()=>void 0),I.set(Xr,()=>void 0)}
Er=0;Dr=1;Or=2;kr=3;Ar=4;jr=5;Mr=6;Nr=7;Pr=8;F=9;Fr=10;Ir=11;Lr=12;Rr=13;zr=14;Br=15;Vr=16;Hr=17;Ur=18;Wr=19;Gr=20;Kr=21;qr=22;Jr=23;Yr=24;Xr=25;Zr=26;Qr=27;$r=28;ei=29;ti=30;ni=33;ri=34;ii=35;I=new Map;ai=0;oi=Promise.resolve();
export { Cr as solveTurnstile };
